[
  {
    currency: "KRW",
    balance: "0.060614",
    locked: "0.0",
    avg_buy_price: "0",
    avg_buy_price_modified: true,
    unit_currency: "KRW",
  },
  {
    currency: "IQ",
    balance: "5118.7845665",
    locked: "0.0",
    avg_buy_price: "39.07",
    avg_buy_price_modified: false,
    unit_currency: "KRW",
  },
  {
    currency: "MED",
    balance: "555.55555556",
    locked: "0.0",
    avg_buy_price: "180",
    avg_buy_price_modified: false,
    unit_currency: "KRW",
  },
  {
    currency: "TT",
    balance: "5392.71750405",
    locked: "0.0",
    avg_buy_price: "27.78",
    avg_buy_price_modified: false,
    unit_currency: "KRW",
  },
  {
    currency: "UPP",
    balance: "643.67588933",
    locked: "0.0",
    avg_buy_price: "232.95",
    avg_buy_price_modified: false,
    unit_currency: "KRW",
  },
  {
    currency: "MBL",
    balance: "5897.53332699",
    locked: "0.0",
    avg_buy_price: "25.43",
    avg_buy_price_modified: false,
    unit_currency: "KRW",
  },
  {
    currency: "OBSR",
    balance: "4088.67222479",
    locked: "0.0",
    avg_buy_price: "36.63",
    avg_buy_price_modified: false,
    unit_currency: "KRW",
  },
  {
    currency: "CRE",
    balance: "3558.71886121",
    locked: "0.0",
    avg_buy_price: "28.1",
    avg_buy_price_modified: false,
    unit_currency: "KRW",
  },
];
